
import React, { useState, useEffect } from 'react';
import Link from "next/link";



const SingleResults = ({ query }) => {
  const Results = query['Results'];
  const Details = query['Details'];

  useEffect(() => {
    var tables = document.getElementsByTagName("table");
    for (var t = 0; t < tables.length; t++) {
      var table = tables[t];

      var rows = table.getElementsByTagName('tr');

      for (var i = rows.length - 1; i >= 0; i--) {
        var row = rows[i];
        var cells = row.getElementsByTagName('th');

        var isEmptyRow = true;

        for (var j = 0; j < cells.length; j++) {
          if (cells[j].innerText.trim() !== '') {
            isEmptyRow = false;
            break;
          }
        }

        if (isEmptyRow) {
          row.parentNode.removeChild(row);
        }
      }

      var cells = table.getElementsByTagName('th');

      for (var j = cells.length - 1; j >= 0; j--) {
        var cell = cells[j];
        var columnIndex = cell.cellIndex;
        var isEmptyColumn = true;

        for (var i = 0; i < rows.length; i++) {
          var row = rows[i];
          var currentCell = row.cells[columnIndex];

          if (currentCell.innerText.trim() !== '') {
            isEmptyColumn = false;
            break;
          }
        }

        if (isEmptyColumn) {
          for (var i = 0; i < rows.length; i++) {
            var row = rows[i];
            row.deleteCell(columnIndex);
          }
        }
      }
    }
  }, []);

  const print = () => {
    setDisplay("hidden")
    setTimeout(function () {
      window.print();
    }, 500);
  }
  const [display, setDisplay] = useState("fixed bottom-8 right-6 sm:right-8 sm:bottom-8 bg-white rounded-full");

  return (
    <>
    <div className='container'>
      {/* <div id="printi" className={display}>
        <img src='./download.png' onClick={print} className="w-[40px]  sm:w-[60px]" />
      </div> */}
      <div className="m-2 text-[45%] sm:text-[60%] md:text-[80%] lg:text-[100%]">
        {Object.keys(Results).map((val, ind) => {
		  if (val!='Total' && val=="1-1"){
			  return <>
			  <center><h2>This File is Auto. Generated by <a style={{color:"red",fontWeight:"Bold"}} href="https://t.me/Jntuhfastresults_bot"> JNTU-H Results Bot...</a></h2></center>
			  <table className="table">
                  <tbody>
                    <tr>
                      {Object.keys(Details).map((value, index) => { return <><th>{value}</th><th>{Details[value]}</th></> })}
                    </tr>
                  </tbody>
                </table>
				<div className='Total'>
				  <table center>
					<tbody >
					  <tr>
						<th className="py-2" style={{fontSize:23,backgroundColor:"green",color:'white', textAlign:'center', width: '50%' ,height:"50px"}}>Total CGPA</th>
						<th className="py-2" style={{fontSize:23,backgroundColor:"red",color:'white', textAlign:'center', width: '50%' ,height:"50px"}}>Total Backlogs</th>
						</tr>
						<tr>
						<th className="py-2" style={{fontSize:48,color:'green',  textAlign:'center', width: '50%' ,height:"100px" }}>{Results['Total']}<br/><p style={{fontSize:'small'}}>Excluding Failed Subjects</p></th>
						
						<th className="py-2" style={{fontSize:48,color:'red',  textAlign:'center', width: '50%' ,height:"100px" }}>{Results['Total Backlogs']}</th>
					  </tr>
					</tbody>
				  </table>
				</div>
				<br/>
				<div id='1'>
                <table className="table">
                  <tbody>
                    <tr>
                      <th>{val} Results</th>
                    </tr>
                  </tbody>
                </table>
                
                <table className="table">
                  <tbody>
                    <tr>
                      <th>SUBJECT_NAME</th>
                      <th>SUBJECT_CODE</th>
                      <th>INTERNAL</th>
                      <th>EXTERNAL</th>
                      <th>TOTAL</th>
                      <th>GRADE</th>
                      <th>CREDITS</th>
                    </tr>
                    {Object.keys(Results[val]).map(function (item, index) {
                      if (item != 'Total' & item != 'Total Backlogs' & item != 'backlogs' & item != 'Total' & item != 'credits') {
                        return <><tr>
                          <th>{Results[val][item]['subject_name']}</th>
                          <th>{Results[val][item]['subject_code']}</th>
                          <th>{Results[val][item]['subject_internal']}</th>
                          <th>{Results[val][item]['subject_external']}</th>
                          <th>{Results[val][item]['subject_total']}</th>
                          <th>{Results[val][item]['subject_grade']}</th>
                          <th>{Results[val][item]['subject_credits']}</th>
                        </tr>
                        </>
                      }
                    })}
                  </tbody>
                </table>
                <table className="table">
                  <tbody>
                    <tr>
                      <th style={{ width: '40%' }}>SGPA</th>
                      <th  style={{ width: '10%' }}>{Results[val]['SGPA']}</th>
					  <th  style={{ width: '40%' }}>Backlogs</th>
                      <th  style={{ width: '10%' }}>{Results[val]['backlogs']}</th>
                    </tr>
                  </tbody>
                </table>
                <br />
              </div>
			  </>
		  }
          if (val != 'Total Backlogs' & val != 'Total') {
            return <>
              <div id='1'>
                <table className="table">
                  <tbody>
                    <tr>
                      <th>{val} Results</th>
                    </tr>
                  </tbody>
                </table>
                
                <table className="table">
                  <tbody>
                    <tr>
                      <th>SUBJECT_NAME</th>
                      <th>SUBJECT_CODE</th>
                      <th>INTERNAL</th>
                      <th>EXTERNAL</th>
                      <th>TOTAL</th>
                      <th>GRADE</th>
                      <th>CREDITS</th>
                    </tr>
                    {Object.keys(Results[val]).map(function (item, index) {
                      if (item != 'Total' & item != 'Total Backlogs' & item != 'backlogs' & item != 'Total' & item != 'credits') {
                        return <><tr>
                          <th>{Results[val][item]['subject_name']}</th>
                          <th>{Results[val][item]['subject_code']}</th>
                          <th>{Results[val][item]['subject_internal']}</th>
                          <th>{Results[val][item]['subject_external']}</th>
                          <th>{Results[val][item]['subject_total']}</th>
                          <th>{Results[val][item]['subject_grade']}</th>
                          <th>{Results[val][item]['subject_credits']}</th>
                        </tr>
                        </>
                      }
                    })}
                  </tbody>
                </table>
                <table className="table">
                  <tbody>
                    <tr>
                      <th style={{ width: '40%' }}>SGPA</th>
                      <th  style={{ width: '10%' }}>{Results[val]['SGPA']}</th>
					  <th  style={{ width: '40%' }}>Backlogs</th>
                      <th  style={{ width: '10%' }}>{Results[val]['backlogs']}</th>
                    </tr>
                  </tbody>
                </table>
				<br />
              </div>
            </>
          }
        })}
		<h2 align="center" style={{color:"red",fontWeight:"bold"}}><a href="http://www.instagram.com/sayikumarr/"> click here to contact Admin </a></h2><br/>
    <h1 className="mt-1 block text-left mx-[12%] text-center mb-4 text-[65%] sm:text-[100%]">
            Made with ❤ by &nbsp;
            <Link href="https://github.com/Sayikumarr/" >
                <a target="_blank" className="font-bold text-[#9C1A8B]" >
                    Sai Kumar Mudhiraj
                </a>
            </Link>
        </h1>
       </div>
      </div>
    </>
  )
}
export default SingleResults



